language: go

go:
  - 1.7.x
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

install:
  - make tools

script: make travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
